export const AT = {
  FETCH_GIF_SUCCESS: 'FETCH_GIF_SUCCESS',
  FETCH_GIF_ERROR: 'FETCH_GIF_ERROR',
  FETCH_GIF_PENDING: 'FETCH_GIF_PENDING',
  ADD_FAVORITE: 'ADD_FAVORITE',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
  FETCH_GIFBYID_SUCCESS: 'FETCH_GIFBYID_SUCCESS',
  FETCH_GIFBYID_PENDING: 'FETCH_GIFBYID_PENDING',
  FETCH_GIFBYID_ERROR: 'FETCH_GIFBYID_ERROR',
};
