export const AT = {
  GET_ALL_CONTACT: 'GET_ALL_CONTACT',
  CONTACT_ERROR: 'CONTACT_ERROR',
  CONTACT_PENDING: 'CONTACT_PENDING',
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  ADD_FAVORITE: 'ADD_FAVORITE',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
  SEARCH_CONTACT: 'SEARCH_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  GET_CONTACT: 'GET_CONTACT',
  DISPLAY_FAVORITE: 'DISPLAY_FAVORITE',
};
